.gitignore, src/y_doc.rs, src/y_map.rs, tests/test_helper.py, tests/test_y_array.py, tests/test_y_doc.py, y_py.pyi
Added documentation and types to the Y-Py API. Allows for static type checking via tools like [MyPy](https://mypy.readthedocs.io/en/stable/) and hover documentation in VSCode:
=> Added type annotations

.gitignore, docs/Makefile, docs/conf.py, docs/index.rst, docs/installation.rst, docs/make.bat, docs/modules.rst, docs/tutorial.rst, y_py.pyi
Added Sphinx Documentation
- Created the `docs` folder to contain the .rst documentation files and build scripts
- Wrote a small package introduction, installation guide, and basic tutorial.
- Used `autoapi` to create documentation from the docstrings in the `y_py.pyi` types file
- Converted from Google Python documentation style to rst style using `napoleon`
- Rewrote the documentation to conform to Google Python documentation style.
To test this out first install sphinx:
```
pip install Sphinx
```
Then navigate to the `docs` folder and run:
```
make html
```
This will produce a Sphinx build. Double click on `docs/_build/html/index` to preview the page.
=> Sphinx docs

Cargo.toml, README.md, docs/tutorial.rst, src/type_conversions.rs, src/y_array.rs, src/y_map.rs, src/y_text.rs, src/y_transaction.rs, src/y_xml.rs, tests/test_y_array.py, tests/test_y_map.py, tests/test_y_text.py, tests/test_y_xml.py, y_py.pyi
Updated libraries and adapted Ypy API to be more Pythonic. The goal of the latter is to make Y types as interoperable as possible with native Python data structures without causing confusion.
- Updated PyO3 to 0.16.2
- Updated Yrs to 0.5.0
- Added `trait Iterator` to several internal type iterators for clarity
- Took out `YTransaction` argument for all read-only functions.
Added native support for:
- Iteration: `[el for el in y_array]`
- Contains: `el in y_array`
- Number indexing: `y_array[0]`
- Range indexing: `y_array[1:3]`
- String `[1,2,3]` and Repr `YArray([1,2,3])` outputs for printing.
- Length operator `len(y_array)`
- Key Iteration: `[key for key in y_map]`
- Key/Value iteration changed from `entries()` to `items()` to match Python dictionary API
- Contains: `key in y_map`
- Key …
=> Updated Ypy API for new Yrs version

.github/workflows/wheels.yml, .gitignore
Updated the deployment workflow to use [Maturin](https://github.com/messense/maturin-action)
- Builds wheels for more platforms including several linux versions, x64 and x86 for windows, and both x86 and M1 for macs
- Includes the `.pyi` type hint file as part of the deployment, which gives type hints and documentation in the IDE
> ~~This still needs to be tested~~ This has been tested on a fork. Everything builds but I have not attempted a real deployment. The current version is based on [an example](https://github.com/adriangb/graphlib2/blob/main/.github/workflows/python.yaml) attached to the [maturin-action](https://github.com/messense/maturin-action) repository.
=> Maturin Deployment Workflow

tests/test_y_text.py
I added a test based on a variation of what was described in #23 . Could not reproduce the invalid behavior locally.
=> Dropped Subscription Id Causing `unobserve` to trigger

src/y_doc.rs
I'm closing #38 and continuing the development of a Ypy websocket provider in https://github.com/davidbrochart/y-websocket.
But I will need to subclass YDoc, hence this PR.
=> Allow to inherit from YDoc

.github/workflows/test.yml, .github/workflows/wheels.yml
Due to #36, we should support at least Python 3.10 in our test and build scripts. I updated the `test` and `wheels` actions to work with both Python 3.7 and ~Python-latest~ Python 3.10.
- Provides an upper and lower bound for supported Python versions
- ~Since the upper bound of the Python version is not pinned, it could lead to unexpected bugs when Anaconda updates their latest Python version.~
=> added latest python to test and build

src/type_conversions.rs, src/y_text.rs, tests/test_y_text.py, y_py.pyi
Fixes #7 
- Added rich text insertion functions
- Added associated tests
- Updated documentation and type hints
=> Added rich text formatting

src/shared_types.rs, src/type_conversions.rs, src/y_array.rs, src/y_map.rs, src/y_text.rs, src/y_xml.rs, tests/test_y_array.py, tests/test_y_map.py, tests/test_y_text.py, tests/test_y_xml.py, y_py.pyi
Fixes #43 
Added deep observe option to all YTypes
```python
sub = y_array.observe(fn)
sub = y_array.observe(fn, deep=True)
```
=> Deep Observe

src/shared_types.rs, src/type_conversions.rs, src/y_array.rs, src/y_map.rs, src/y_text.rs, tests/test_y_array.py, tests/test_y_doc.py, tests/test_y_map.py, tests/test_y_text.py, y_py.pyi
- YMap.delete -> YMap.pop: Reflects the dict api. Pop returns the removed value and throws a key error if it doesn't find a value.
- Added YMap.get: gets value from array with optional default value.
- YArray.delete -> YArray.delete_range
- YArray.insert -> YArray.insert_range: Now takes any iterable
- Added YArray.insert: Inserts a single element at index
- Added YArray.append: adds value to the end of the list
- Added YArray.delete: Deletes individual value
- `py_into_any` refactored with more explicit error handling. Instead of returning `None` on error conditions, it now returns either a `MultipleIntegrationError` when attempting to integrate a non preliminary value and a `TypeError` when the supplied type cannot be integrated into YCRDT as `Any`. This centralizes the definition of …
=> Updated YMap and YArray API

README.md, src/y_doc.rs, tests/test_y_doc.py, y_py.pyi
Adds the `after_transaction_cleanup` event
- Event exposes the encoded state vectors of a transaction
- `before_state`
- `after_state`
- `delete_set`
This allows communication providers to subscribe to updates and send diffs to other users over the network.
**Note:** It is not currently possible to unsubscribe from this hook. Once there is a release of ycrdt with this pr, we'll add an `unobserve` method equivalent to `YDoc`.
=> YDoc Transaction Cleanup Hook

src/y_doc.rs, src/y_transaction.rs, tests/test_y_transaction.py, y_py.pyi
Fixes #40
- Before state is cached on the YTransaction object as a dictionary map between client Id and pointer. Requires iterating through internal representation of before state, so the result is cached in case it is referenced multiple times.
- Added basic tests
=> Added `before_state` as a `YTransaction` property

src/lib.rs, src/y_array.rs, src/y_map.rs, src/y_text.rs, src/y_xml.rs, tests/test_y_array.py, tests/test_y_map.py, tests/test_y_text.py, y_py.pyi
Fixes #55
- All events have a string representation
- Removed extraneous `delta` prop in `YMapEvent`
- Fixed `YMapEvent` typo that said YText
- Improved `YMapEvent` types and documentation.
=> More Transparent Events

src/y_map.rs, tests/test_y_map.py, y_py.pyi
Fixes #58
To more closely mirror the functionality of dict.items(), YMap.items() now returns an ItemsView:
- Stays up to date with changes in the YMap
- Supports length and membership checks in constant time
- Supports multiple iterations, instead of getting exhausted like a standard iterator.
=> YMap Items View

src/lib.rs, src/type_conversions.rs, src/y_doc.rs, src/y_transaction.rs, tests/test_y_doc.py, y_py.pyi
Adds the `get_update` method to the AfterTransactionEvent so that delta state is accessible in the `observe_after_transaction` callback.
Fixes #69 
- Updated some YDoc methods to not require mutable access.
- Exposed AfterTransactionEvent to library users.
- Reduced blanket `ToPython` array impl to just handle Vec<Any>
- Added test to verify `get_update`
=> After Transaction Update

pyproject.toml, src/shared_types.rs, src/type_conversions.rs, src/y_array.rs, src/y_map.rs, src/y_text.rs, tests/test_y_map.py
Minor refactor of the codebase:
- Moved the `py_into_any` function into the `PyObjectWrapper` class as a `try_from` trait operation. This centralizes the type conversions to a single type, but could also make the code slightly less readable.
- Deleted `PyValueWrapper` which was identical to `PyObjectWrapper` and just acted as bloat.
- Updated wrapper types to use `#[repr(transparent)]`. This should more aggressively optimize away the wrapper types.
- Added upper version bound to `maturin` so it won't break our distribution system by surprise again.
=> Wrapper Refactor

y_py.pyi
Small docstring mismatch I noticed while trying out this cool library.
=> applyV1 should be apply_v1

src/y_array.rs, tests/test_y_array.py, y_py.pyi
Hi @Waidhoferj.
I noticed the move feature had not yet been implemented here in the python bindings. I trying to implement it since we need it for JupyterLab.
Can you take a look at this? It is the first time I have looked at y-rs and y-py, and the first time I used rust, so I'm unsure if I'm implementing it correctly.
I'm keeping the PR as a draft because I want to implement `move_range_to` in the same PR, but first, I would like you to take a look at the `move_to` function in case I'm doing something wrong.
=> Implements move_to

README.md
There's a couple badges I like to have at the top of README's in my repos, thought I'd start with adding in a simple pypi link to see what you all thought of them. Happy to include more in this PR or leave them off the project, either way.
(`pydantic-core` for comparison as another Python/Rust hybrid repo on pypi -- *to be clear I'm not a contributor there*. The different style/text between the top and bottom picture is a difference in using badge.fury.io vs shield.io, I don't have a real preference between them)
=> Add Pypi badge to README

.github/workflows/test.yml, Cargo.toml, README.md, pyproject.toml, setup.cfg, setup.py
Alternative to, and closes https://github.com/y-crdt/ypy/pull/86 if you prefer this one.
Use `hatch` to manage Python virtualenv when developing instead of manually creating one or re-using a system Python. 
This is what I'm seeing in the wheel metadata after building
=> Hatch to manage Python virtualenvs

.github/workflows/test.yml, .github/workflows/wheels.yml, README.md, pyproject.toml
Closes https://github.com/y-crdt/ypy/issues/96
The way this should work is that when we create a release via the Github UI (Releases -> draft new release -> create new tag like `v0.5.6`), that will trigger CI and build wheels / upload to Pypi like normal. In addition, it will build the `emscripten` / wasm wheel and upload that as an asset to the Release. 
- `emscripten` / WASM wheels will be built and the artifacts uploaded to a separate CI namespace than the other wheels (`wasm_wheel` vs `wheels`)
- A new job in CI that only runs on tagged releases will pull in the wasm wheel binaries and upload them as assets to the release with the same name as the git tag
- Had to remove the dependencies in pyproject.toml in order to import the wasm wheel in pyodide (`maturin` has no pure Python …
=> Attach emscripten / wasm wheels to Release as assets

src/json_builder.rs, src/lib.rs, src/shared_types.rs, src/type_conversions.rs, src/y_array.rs, src/y_map.rs, src/y_text.rs, tests/test_y_array.py, tests/test_y_doc.py, tests/test_y_map.py, y_py.pyi
Updates `to_json` methods to return `str` types so that they can be used with Python `json`
Fixes #85 
- Separated type validation into `CompatiblePyType`, which validates incoming Python types to ensure they can be represented in the YCRDT.
- Added `JsonBuilder`, which can append json from any `JsonBuildable` object to a string buffer.
- Updated tests to cover `to_json` conversion.
- Changed `YArray` iterator method to return a PyIterator on eagerly evaluated array contents.
In the past, we used `to_json` as a conversion to native Python types. In the future, we should use the direct constructor of the type we desire:
```python
python_list = list(y_array)
python_dict = dict(y_map)
python_string = str(y_text)
```
Note that this is not a deep conversion.
This addresses an unknown bug …
=> `to_json` compatibility with Python `json`

.github/workflows/wheels.yml, pyproject.toml
Fixes for the failures we saw in https://github.com/y-crdt/ypy/pull/115 / https://github.com/y-crdt/ypy/actions/runs/4167129650
- Bump maturin version for building wheels
- Build on PR as well as release, so we can see these errors before trying to cut a release (see checks below)
- Run test suite after build
- Basically copy what is in `py-dissimilar` CI https://github.com/messense/py-dissimilar/blob/main/.github/workflows/CI.yml
- macos job is slower than the others, maybe related to https://github.com/actions/runner-images/issues/3885
- Windows pypy builds threw errors so I took those out, we weren't building those before though
=> Build aarch64 take 2

pyproject.toml
The v0.5.7 github release built wheels correctly (thank goodness, finally) but parts of the push to pypi failed because pyproject.toml version was still 0.5.5 and there were wheels on pypi for 0.5.5 already https://github.com/y-crdt/ypy/actions/runs/4188025953/jobs/7259030230. There are now some y_py 0.5.5 wheels uploaded Dec 13 2022 and (the new aarch64) wheels uploaded Feb 15 2023 https://pypi.org/project/y-py/0.5.5/#files. 
One option is to bump the version in pyproject.toml from 0.5.5 to 0.5.8 so that we don't have to delete and recreate releases in github -- there would just be "missing" wheels on p ypi for 0.5.6 / 0.5.7. @Waidhoferj I'm also fine if you want to close this PR, delete the previous github releases, bump pyproject.toml to 0.5.6 and recreate the github v0.5.6 release. …
=> Bump version to create github v0.5.8 release and upload pypi wheels?

src/y_transaction.rs
The `drop(self)` issues a warning:
```
warning: calls to `std::mem::drop` with a reference instead of an owned value does nothing
--> src/y_transaction.rs:263:9
|
263 |         drop(self);
|         ^^^^^----^
|              |
|              argument has type `&mut YTransaction`
|
= note: use `let _ = ...` to ignore the expression or result
= note: `#[warn(dropping_references)]` on by default
```
=> Remove drop reference
